# single tokens or currencies
BAL_TICKER = 'BAL'
BTC_TICKER = 'BTC'
COMP_TICKER = 'COMP'
ETH_TICKER = 'ETH'
LINK_TICKER = 'LINK'
OVL_TICKER = 'OVL'
USD_TICKER = 'USD'
YFI_TICKER = 'YFI'

# pairs of tokens (exchange rates)
BAL_USD_TICKER = f'{BAL_TICKER}-{USD_TICKER}'
BTC_USD_TICKER = f'{BTC_TICKER}-{USD_TICKER}'
COMP_USD_TICKER = f'{COMP_TICKER}-{USD_TICKER}'
ETH_USD_TICKER = f'{ETH_TICKER}-{USD_TICKER}'
LINK_USD_TICKER = f'{LINK_TICKER}-{USD_TICKER}'
OVL_USD_TICKER = f'{OVL_TICKER}-{USD_TICKER}'
YFI_USD_TICKER = f'{YFI_TICKER}-{USD_TICKER}'
