# single tokens or currencies
BAL_TICKER = 'BAL'
BTC_TICKER = 'BTC'
COMP_TICKER = 'COMP'
ETH_TICKER = 'ETH'
LINK_TICKER = 'LINK'
OVL_TICKER = 'OVL'
USD_TICKER = 'USD'
YFI_TICKER = 'YFI'
TRX_TICKER = 'TRX'
MKR_TICKER = 'MKR'
ETC_TICKER = 'ETC'
ADA_TICKER = 'ADA'
EOS_TICKER = 'EOS'
SNX_TICKER = 'SNX'
XRP_TICKER = 'XRP'
USDT_TICKER = 'USDT'


def ovl_quote_ticker(quote: str):
    return f'{OVL_TICKER}-{quote}'


# pairs of tokens (exchange rates)
# USD quote
BAL_USD_TICKER = f'{BAL_TICKER}-{USD_TICKER}'
BTC_USD_TICKER = f'{BTC_TICKER}-{USD_TICKER}'
COMP_USD_TICKER = f'{COMP_TICKER}-{USD_TICKER}'
ETH_USD_TICKER = f'{ETH_TICKER}-{USD_TICKER}'
LINK_USD_TICKER = f'{LINK_TICKER}-{USD_TICKER}'
XRP_USD_TICKER = f'{XRP_TICKER}-{USD_TICKER}'
OVL_USD_TICKER = f'{OVL_TICKER}-{USD_TICKER}'
YFI_USD_TICKER = f'{YFI_TICKER}-{USD_TICKER}'

# USDT quote
ADA_USDT_TICKER = f'{ADA_TICKER}-{USDT_TICKER}'
BTC_USDT_TICKER = f'{BTC_TICKER}-{USDT_TICKER}'
EOS_USDT_TICKER = f'{EOS_TICKER}-{USDT_TICKER}'
ETC_USDT_TICKER = f'{ETC_TICKER}-{USDT_TICKER}'
ETH_USDT_TICKER = f'{ETH_TICKER}-{USDT_TICKER}'
MKR_USDT_TICKER = f'{MKR_TICKER}-{USDT_TICKER}'
SNX_USDT_TICKER = f'{SNX_TICKER}-{USDT_TICKER}'
TRX_USDT_TICKER = f'{TRX_TICKER}-{USDT_TICKER}'
XRP_USDT_TICKER = f'{XRP_TICKER}-{USDT_TICKER}'

# BTC quote
ADA_BTC_TICKER = f'{ADA_TICKER}-{BTC_TICKER}'
EOS_BTC_TICKER = f'{EOS_TICKER}-{BTC_TICKER}'
ETH_BTC_TICKER = f'{ETH_TICKER}-{BTC_TICKER}'
ETC_BTC_TICKER = f'{ETC_TICKER}-{BTC_TICKER}'
MKR_BTC_TICKER = f'{MKR_TICKER}-{BTC_TICKER}'
SNX_BTC_TICKER = f'{SNX_TICKER}-{BTC_TICKER}'
TRX_BTC_TICKER = f'{TRX_TICKER}-{BTC_TICKER}'
XRP_BTC_TICKER = f'{XRP_TICKER}-{BTC_TICKER}'

# ETH quote
EOS_ETH_TICKER = f'{EOS_TICKER}-{ETH_TICKER}'
ETC_ETH_TICKER = f'{ETC_TICKER}-{ETH_TICKER}'
MKR_ETH_TICKER = f'{MKR_TICKER}-{ETH_TICKER}'
SNX_ETH_TICKER = f'{SNX_TICKER}-{ETH_TICKER}'
TRX_ETH_TICKER = f'{TRX_TICKER}-{ETH_TICKER}'
XRP_ETH_TICKER = f'{XRP_TICKER}-{ETH_TICKER}'
